targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - unnecessary_null_checks
            - require_trailing_commas
            - lines_longer_than_80_chars
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      json_serializable:
        options:
          field_rename: snake