name: flutter_training
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4

  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  blendthink_lints: ^3.0.0
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0

flutter:
  uses-material-design: true

  generate: false

  assets:
    - assets/images/